### ISSUE TITLE
issue for tracking repos with papers to be updated 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/appliedgeophysics.org#8]
@tetikshajain: I am starting a "global" issue here where we can track repositories where we are putting papers up. I will list the repositories here that I get started with and could you please check them off when you are done with each? 

- [ ]  https://github.com/ubcgif/2021-oldenburg-etal-tle-disc

**Comment by lheagy** [comment]
Awesome to see all of the checkmarks @tetikshajain! Next up, lets tackle some presentations. I will share the google drive folder that contains these and create a list here of the presentations to be archived. For each of these, please include the abstract, original ppt file (if it exists) and the pdf of the presentation / poster. The pdf is what we will link on the site. For thumbnails, you can take a screen-grab from the poster or slides of a figure that you like.  

- [ ] 2024-04-SEGUXOsummit. Presented as a part of "Summit on Geophysical Detection of Explosive Remnants of War: Solving Current Challenges of Unexploded Ordnance (UXO) and Demining" (https://seg.org/calendar_events/summit-on-geophysical-detection-of-explosive-remnants-of-war-solving-current-challenges-of-unexploded-ordnance-and-demining/)  
- [ ] 2024-03-SAGA. This was a presentation for the "Southern African Geophysical Society". We can include the recording that is available here: https://youtu.be/RoNDkSiIXfU?si=Hxuo45N0hkNU5acN
- [ ] 2024-01-Roundup. You can ask Devin if he has an abstract for this 
- [ ] 2023-12-AGU. There are multiple abstracts here. We can create a different repository for each. These were presented as a part of the American Geophysical Union conference (https://agu.confex.com/agu/fm23/meetingapp.cgi/Home/0). You can ask Anran if she has a link to the e-poster she presented
- [ ] 2023-11-SERDP. I will find the abstract for this. This was presented as a part of the 2023 SERDP-ESTCP-OEC symposium (https://serdp-estcp.mil/events/details/04d444f1-aa19-4e66-bb5c-5163964cc4dd/symposium-2023)
- [ ] 2023-08-IMAGE. There are multiple presentations in here, we can create a repository for each. Conference URL: https://library.seg.org/doi/book/10.1190/segeab.42
- [ ] 2023-04-SAGEEP. Conference info is here: https://www.eegs.org/proceedings-sageep-2023
- [ ] 2023-01-Geotech-symposium (I will see if I can find the abstract for you) 
- [ ] 2022-UTasmania. Seminar presented to the University of Tasmania 
- [ ] 2022-SERDP. conference website: https://www.google.com/search?q=2022+SERDP&sourceid=chrome&ie=UTF-8
- [ ] 2022-BCGS-roundup-breakfast. This one was recorded on youtube, and we can include the recording here: https://youtu.be/B6ZaiwcUaFA?si=DLskec_H_-_wS6mO
- [ ] 2022-BAGS-CSM. Presented as a part of the Bay Area Geophysical Society seminars on the Future of Applied Geophysics. https://bayareageophysicalsociety.org/future-of-applied-geophysics-seminar-series-tools/
- [ ] 2022-AGU. There are multiple abstracts here. Each can be a separate repository  

Separately, here is a list of todo's on my plate 
- [ ] 2024-02-Agrogeophysics
- [ ] 2023-09-AEM
- [ ] 2023-03-KEGS
- [ ] 2023-03-AEGC
- [ ] 2022-SEG
- [ ] 2022-PDAC. conference website: https://www.pdac.ca/convention/attendee-info/past-conventions/2022-convention

**Comment by lheagy** [comment]
We can use this tread to track the papers that have appendices that should be updated:
- [ ] https://github.com/ubcgif/2021-astic-etal-gji
- [ ] https://github.com/ubcgif/2023-heagy-oldenburg-gji-casing-permeability

There might be a few others
